### ISSUE TITLE
nano 33 IoT support

### ISSUE THREAD

**Issue by pokauppi** [MartinL1/I2C_DMAC#10]
Hi, I noticed that the board in question seems to also require the same initialization call as the Metro M4 board: `I2C.begin(400000, REG_ADDR_8BIT, PIO_SERCOM_ALT);`

Is this to be expected, or is there maybe something else that could cause the SERCOM to hang?

**Comment by MartinL1** [comment]
@pokauppi Looking at the Nano 33 IoT schematic, this is to be expected. The Nano 33 IoT uses I2C on port pins PB08 and PB09, which like the Metro M4 are assigned to the PIO_SERCOM_ALT multiplexer switch.

Thank you for flagging this up, it's something I need to document in the README.md file.

Is your I2C bus hanging? What device are you connected to?

**Comment by pokauppi** [comment]
I sometimes experience hangs (once in two hours or so, with 30 packets being sent every second), but it is likely to be a signal quality issue as I have a number of identical LED drivers (IS31FL3236) I'm communicating with and the hangs don't seem to happen with all of them. There is also a PCA9548A on the bus. I think I'll just need to implement some routine to reset the i2c router via GPIO if a hang is detected.

A problem that I do have is with using the WLAN at the same time. For whatever reason when I get new variable values from the Blynk service the connection drops and the whole program seems to hang. I'm thinking there could be some interrupt handling related issues at play, but I need to investigate further.
