### ISSUE TITLE
Adafruit SeeSaw Communication

### ISSUE THREAD

**Issue by DigiMaxIO** [MartinL1/I2C_DMAC#11]
Hello, 
First off, love this library and appreciate all of your efforts on this.

Hoping you could help me out with implementing this Lib to communicate with the Adafruit Seesaw. My code is based on the Adafruit library, which, of course, uses the Wire library along with buffers. However, I'm having some trouble converting some of the functions to use this library; I've gotten partway there with the code below, (which does compile) but when serial printing the buttons' status, the correct data is displayed (same as the Adafruit library), however, that data doesn't change when any of the buttons are pressed. Let me know if you have any insight on how to improve upon this. 

Here's a link if you need more information:
[Reading and Writing Data With the Adafruit SeeSaw](https://learn.adafruit.com/adafruit-seesaw-atsamd09-breakout/reading-and-writing-data)

`//#include <Wire.h>
#include <I2C_DMAC.h>
//#include "Adafruit_seesaw.h"

#define BUTTON_RIGHT 6
#define BUTTON_DOWN  7
#define BUTTON_LEFT  9
#define BUTTON_UP    10
#define BUTTON_SEL   14
uint32_t button_mask = (1 << BUTTON_RIGHT) | (1 << BUTTON_DOWN) | 
                (1 << BUTTON_LEFT) | (1 << BUTTON_UP) | (1 << BUTTON_SEL);

#define IRQ_PIN   11

void setup() {
  while (!Serial) { delay(10); }
  Serial.begin(115200);
  
  I2C.begin(100000);
  
  i2cwrite8(0x00, 0x7F, 0xFF);
  delay(500);
  
  Serial.print("version: ");
  Serial.println(ssgetVersion(), HEX);
  
  pinModeBulk(button_mask, INPUT_PULLUP);
  setGPIOInterrupts(button_mask, 1);
  pinMode(IRQ_PIN, INPUT);
}

void loop() {
  uint32_t buttons = digitalReadBulk(button_mask);

  Serial.print((buttons & (1 << BUTTON_RIGHT))); 
  Serial.print((buttons & (1 << BUTTON_DOWN)));
  Serial.print((buttons & (1 << BUTTON_LEFT)));
  Serial.print((buttons & (1 << BUTTON_UP)));
  Serial.println((buttons & (1 << BUTTON_SEL)));

  if (! (buttons & (1 << BUTTON_RIGHT))) {
      Serial.println("Button A pressed");
    }
    if (! (buttons & (1 << BUTTON_DOWN))) {
      Serial.println("Button B pressed");
    }
    if (! (buttons & (1 << BUTTON_LEFT))) {
      Serial.println("Button Y pressed");
    }
    if (! (buttons & (1 << BUTTON_UP))) {
      Serial.println("Button X pressed");
    }
    if (! (buttons & (1 << BUTTON_SEL))) {
      Serial.println("Button SEL pressed");
    }
  delay(10);
  
}

bool ssdigitalRead(uint8_t pin) {
  if (pin < 32)
    return digitalReadBulk((1ul << pin)) != 0;
}

void i2cread(uint8_t regHigh, uint8_t regLow, uint8_t *buf, uint8_t num, uint16_t delay=125) 
{
  uint8_t pos = 0;
  while (pos < num)
  {
    uint8_t read_now = min(32, num - pos);
    //Wire.beginTransmission(0x49);
    I2C.writeRegAddr(0x49, regHigh); //Wire.write(regHigh);
    while(I2C.writeBusy);
    I2C.writeRegAddr(0x49, regLow);  //Wire.write(regLow);
    while(I2C.writeBusy);
    delayMicroseconds(delay);        //Wire.endTransmission();
    I2C.readByte(0x49, read_now);    //Wire.requestFrom(0x49, read_now);
    //I2C.readBytes(0x49, read_now, buf, pos);
    
    //I2C.getData();
    for (int i = 0; i < read_now; i++) 
    {
      buf[pos] = I2C.getData();//Wire.read();
      pos++;
    }
    while(I2C.readBusy);
  }
}

uint32_t ssgetVersion() {
  uint8_t buf[4];
  i2cread(0x00, 0x02, buf, 4);
  uint32_t ret = ((uint32_t)buf[0] << 24) | ((uint32_t)buf[1] << 16) |
                 ((uint32_t)buf[2] << 8) | (uint32_t)buf[3];
  return ret;
}

uint32_t digitalReadBulk(uint32_t pins) {
  uint8_t buf[4];
  i2cread(0x01, 0x04, buf, 4);
  uint32_t ret = ((uint32_t)buf[0] << 24) | ((uint32_t)buf[1] << 16) |
                 ((uint32_t)buf[2] << 8) | (uint32_t)buf[3];
  return ret & pins;
}

void i2cwrite(uint8_t regHigh, uint8_t regLow, uint8_t *buf, uint8_t num) 
{
  //Wire.beginTransmission(0x49);
  
  I2C.writeRegAddr(0x49, regHigh);//Wire.write(regHigh);
  while(I2C.writeBusy);
  I2C.writeRegAddr(0x49, regLow);//Wire.write(regLow);
  while(I2C.writeBusy);
  I2C.initWriteBytes(0x49, (uint8_t *)buf, num);//Wire.write((uint8_t *)buf, num);
  I2C.write();
  while(I2C.writeBusy);
  //Wire.endTransmission();
}

void i2cwrite8(byte regHigh, byte regLow, byte value) 
{
  i2cwrite(regHigh, regLow, &value, 1); 
}

void pinModeBulk(uint32_t pins, uint8_t mode) {
  uint8_t cmd[] = {((uint8_t)pins >> 24), ((uint8_t)pins >> 16),
                   ((uint8_t)pins >> 8), (uint8_t)pins};
  switch (mode) {
  case OUTPUT:
    i2cwrite(0x01, 0x02, cmd, 4);
    break;
  case INPUT:
    i2cwrite(0x01, 0x03, cmd, 4);
    break;
  case INPUT_PULLUP:
    i2cwrite(0x01, 0x03, cmd, 4);
    i2cwrite(0x01, 0x0B, cmd, 4);
    i2cwrite(0x01, 0x05, cmd, 4);
    break;
  case INPUT_PULLDOWN:
    i2cwrite(0x01, 0x03, cmd, 4);
    i2cwrite(0x01, 0x0B, cmd, 4);
    i2cwrite(0x01, 0x06, cmd, 4);
    break;
  }
}

void setGPIOInterrupts(uint32_t pins, bool enabled) {
  uint8_t cmd[] = {((uint8_t)pins >> 24), ((uint8_t)pins >> 16),
                   ((uint8_t)pins >> 8), (uint8_t)pins};
  if (enabled)
    i2cwrite(0x01, 0x08, cmd, 4);
  else
    i2cwrite(0x01, 0x09, cmd, 4);
}

`
[SeeSaw_CustomI2C.zip](https://github.com/MartinL1/I2C_DMAC/files/5505594/SeeSaw_CustomI2C.zip)

**Comment by MartinL1** [comment]
Hi DigiMaxIO,
I'm closing this issue, as the subject is concerning the integration of the I2C_DMAC library, rather than the library itself.
