### ISSUE TITLE
detachSercomErrorCallback() nulls wrong callback

### ISSUE THREAD

**Issue by hexeguitar** [MartinL1/I2C_DMAC#2]
a small copy/paste error in function (I2C_DMAC.cpp line 566)
```
void I2C_DMAC::detachSercomErrorCallback()
{
	errorDmacCallback = 0;		// Detach the SERCOM error callback function
}
```
`errorDmacCallback` should be replaced with `errorSercomCallback`.

**Comment by MartinL1** [comment]
@hexeguitar Thank you for your correction, I'll update this change to the library shortly.
