### ISSUE TITLE
Compile error when adding library

### ISSUE THREAD

**Issue by felipemcg** [MartinL1/I2C_DMAC#7]
Hello! first of all, i would like to thank you for sharing this library. 
I'm trying to add this library into a simple sketch, using Atmel Studio 7.0 as IDE. The board definition i'm using is Arduino Zero (Programming Port). When I compile the project including the library, I get 19 errors, of 2 types, 'dmacdescriptor' does not name a type and was not declared in this scope. 

My sketch is the following: 
```
#include <Arduino.h>
#include <I2C_DMAC.h>

void setup()
{
	I2C.begin(400000);
}

void loop()
{

}
```

The errors: 
![imagen](https://user-images.githubusercontent.com/9245211/61820942-17088200-ae24-11e9-9847-0e5866d640ce.png)

**Comment by MartinL1** [comment]
@felipemcg 

I downloaded and installed the I2C_DMAC code from this repository and compiled the following sketch on the Arduino IDE for the Arduino Zero (Programming Port). It compiled OK with the verbose setting turned on and produced no errors or warnings. Here's the sketch:

```
#include <I2C_DMAC.h>

void setup() {
  I2C.begin(400000);
}

void loop() {}
```
The issue must have something to do with Atmel Studio 7.
