### ISSUE TITLE
Idea : Any chance to see an example for  the SSD1306 display ?

### ISSUE THREAD

**Issue by deladriere** [MartinL1/I2C_DMAC#9]
This would be really great !

**Comment by MartinL1** [comment]
@deladriere Unfortunately, I don't have an example for the SSD1306 display. 

The I2C_DMAC library is the basis that provides a non-blocking, concurrrent means of I2C communications using the microcontroller's DMAC, upon which other libraries can be built; in the same way that the Arduino Wire library is mearly the basis of I2C communication for other libraries, for example Adafruit's SSD1306 Display Driver library.

Although my custom flight control boards pictured in the title use the I2C_DMAC library for sensor communications, they instead use SPI for their SSD1306 displays. The reason being, is that the SPI communication is faster and is better suited to transferring the 1K byte frame buffer as a single block of data. By contrast, the Wire library on the SAMD21/51, like I2C_DMAC, is limited to a maximum transfer of only 256 bytes, making it less efficient.  On the I2C_DMAC library this 256 byte limit is a hardware limitation.

Saying that, it should be possible to replace the Wire library with I2C_DMAC library, by hacking a SSD1306 display driver, such as Adafruit's example.

**Comment by doctea** [comment]
After much searching I come across this post asking for exactly what I need to do!

I don't suppose you have any pointers on where I should start reading to learn out to hack the Adafruit example to use this library instead?  I'm new to I2C, SSD1306 and DMA and finding it hard to understand where to even get started and at what 'layer' the library needs to be replaced.

Thanks for any help anyone can offer :)
